<?php

return [
    'VEGUNIT' => [
        'JOBGUID',
        'STATNAME',
        'SEQUENCE',
        'UNITGUID',
        'UNIT',
        'ACCDATE',
        
        'ADDRESS',
      
        'ASSLAT',
        'ASSLONG',
        'ASSNOTE',
     
        'AUDIT_FAIL',
        'AUDIT_PASS',
        'AUDIT_USER',
        'AUDITDATE',
        'AUDITNOTE',
    
        'CITY',
  
        'CREWNOTES',
        'CULVERTS',
        'CUSTOMERID',
        'DBHCATG',

        'DNGRTREE',
        'FENCES',
        'FIRSTNAME',
     
        'FORESTER',
    
        'FRSTR_USER',
  
        'GATES',
  
        'HAZ_NOTES',
        'HAZRD_TYPE',
        'HEALTH',
    
        'LASTNAME',

        'NOCULVERTS',
        'NOEROSION',
        'NOFENCES',
        'NOGATES',
        'NOLOADS',
        'NOTIFYDONE',

        'OBJECTID',
        'ONOFF',
        'ORIGJBGUID',

        'PHONE',
        'PLAN_END',
        'PRIORITY',

        'REEVALUATE',
        'REFDATE',
        'REFREASON',
        'REFSLCMNT',
        'REFTYPE',
        'REFUSALYN',
        'REMTREE',

        'ROWPRCNT',

        'SPECIES',
        'STONEROAD',
        'STUMPHERB',
        'TADDRESS',
        'TCITY',
        'TFIRSTNAME',
        'TLASTNAME',
        'TPHONE',
        'TRASH',
        'TREATTYPE',
        'UNIT_CLASS',
        'VEGHERB',

        'DUEDATE',
        'CUSTOMSTATUS',
        'COMMENTS',
        'NOT2FY',

        'FROMSTR',
        'TOSTR',
        'SITEID',

        'AUDITPF',
        'AUDITCOMMENTS',
        'STATE',
        'TOWN',
        'PADDRESS',
        'ZIPCODE',
        'DATEPOP',
        'OBJECTION',
        'PERMSTAT',
        'NOTIFTYPE',
        'TREEOWN',
        'EQUPTYPE',
        'REMOVCAT',
        'APPRXHGHT',
        'INSDEASE',
        'REMVWOOD',
        'STMPTRTM',
        'REMCOMM',
        'CREWTYPE',
        // 'RESTRICT',
        'ACCESCOM',
        'PRIHABITAT',
        'LAND_USE',

        'LASTEDITBY',
        'LASTEDITDT',


        'NOTIFDATE',

        'SPECIESCOM',
        'CUST_EMAIL',
        'POLE_A',
        'POLE_B',
        'CFIRSTNAME',
        'CLASTNAME',
        'CADDRESS',
        'CPHONE',
        'CCITY',
        'CSTATE',
        'TSTATE',
        'CZIP',
        'TZIP',

        'BUSINESS',
        'PERM_REQ',
        'PERM_COMP',

        'DESIGNATION',
        'AUDIT_FAIL_HIST',
        'AUDIT_FAIL_DATE',
        'AUDIT_FAIL_CONTRACTOR_COMPANY',
        'AUDIT_FAIL_CONTRACTOR_USER',
        'COSTMETHOD',
        'ADDEDWORK',
        'ADDEDWORKUSER',
        'ADDEDWORKDATE',
        'BACKTOVW',
        'COUNTY',
        'HERBTRDNM',
        'TGTSPCS',
        'PRI_QT_USE',
        'PRI_OZ_USED',
        'HERBTRDNM2',
        'SEC_QT_USED',
        'SEC_OZ_USED',
        'HERBTRDNM3',
        'TERT_QT_USED',
        'TERT_OZ_USED',
        'HERBTRDNM4',
        'QUAT_QT_USED',
        'QUAT_OZ_USED',
        'WORKUNITGUID',
        'ORIGINAL_UNITGUID',
        'PARCELCOMMENTS',
        'WO',
        'EXT',
        'EDITDATE',
    ],

    'Stations' => [
        'STATNAME',
        'SPANLGTH',
    ],
];
